
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'vbi_crm'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'vbicrm'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  vbi_crm:
      # Applies to all files under models/example/
      vars:
        environment_name: "dev"
        limit_flag: 1
      stage:
        stage_clicky:
          tags: "clicky_stage"
          materialized: view
        stage_wordpress:
          tags: "wordpress_stage"
          materialized: view
      star:
        star_clicky:
          tags: "clicky"
          history:
            tags: "clicky-history"
            materialized: table
          current:
            tags: "clicky-current"
            materialized: table
          currentview:
            tags: "clicky-current_view"
            materialized: view
        star_wordpress:
          tags: "wordpress"
          history:
            tags: "wordpress-history"
            materialized: table
          current:
            tags: "wordpress-current"
            materialized: table
          currentview:
            tags: "wordpress-current_view"
            materialized: view

