select 
    SRC:"id"::number as "id",
    SRC:"date"::timestamp as "date",
    SRC:"date_gmt"::timestamp as "date_gmt",
    SRC:"guid"."rendered"::varchar as "guid",
    SRC:"modified"::timestamp as "modified",
    SRC:"modified_gmt"::timestamp as "modified_gmt",
    SRC:"slug"::varchar as "slug",
    SRC:"status"::varchar as "status",
    SRC:"type"::varchar as "type",
    SRC:"link"::varchar as "link",
    SRC:"title"."rendered"::varchar as "title",
    SRC:"content"."protected"::boolean as "content_protected",
    SRC:"content"."rendered"::varchar as "content",
    SRC:"excerpt"."protected"::boolean as "excerpt_protected",
    SRC:"excerpt"."rendered"::varchar as "excerpt",
    SRC:"author"::number as "author",
    SRC:"featured_media"::number as "featured_media",
    SRC:"parent"::number as "parent",
    SRC:"menu_order"::number as "menu_order",
    SRC:"comment_status"::varchar as "comment_status",
    SRC:"ping_status"::varchar as "ping_status",
    SRC:"template"::varchar as "template",
    SRC:"meta"::variant as "meta",
    SRC:"_links"::variant as "_links",
    "RECORD_CAPTURED_TIME"
from {{ source('wordpress_sources', 'TB_PAGES_DOCUMENT')}}