version: 2

sources:
  - name: clicky_sources
    database: raw
    schema: clicky
    tables:
      - name: campaigns_document
      - name: pages_document
      - name: pages_entrance_document
      - name: pages_exit_document
      - name: searches_engines_document
      - name: searches_keywords_document
      - name: searches_unique_document
      - name: traffic_sources_document
      - name: visitors_list_document
      - name: domain_information_document
      - name: actions_list_document